// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Grafikus_rest_api;
//
//    var api = Api.FromJson(jsonString);

namespace Grafikus_rest_api
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Api
    {
        [JsonProperty("id")]
        public long ApiId { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string ApiName { get; set; }

        [JsonProperty("salary", NullValueHandling = NullValueHandling.Ignore)]
        public long? ApiSalary { get; set; }

        [JsonProperty("position", NullValueHandling = NullValueHandling.Ignore)]
        public string ApiPosition { get; set; }

        [JsonProperty("Id", NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        [JsonProperty("Name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("Salary", NullValueHandling = NullValueHandling.Ignore)]
        public long? Salary { get; set; }

        [JsonProperty("Position", NullValueHandling = NullValueHandling.Ignore)]
        public string Position { get; set; }
    }

    public partial class Api
    {
        public static Api[] FromJson(string json) => JsonConvert.DeserializeObject<Api[]>(json, Grafikus_rest_api.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Api[] self) => JsonConvert.SerializeObject(self, Grafikus_rest_api.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
